GET http://localhost:8080/api/products 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJGYWJyaXppbyIsImV4cCI6MTc3NDg4NzkxOCwianRpIjoiYTYzZWNkYmQzOGU4ZmE0OWU0MGQ0ODg3MzMwZjg3MzQifQ.IfEQE2zJUFhsVsagLU_ulLPgumuxZezw9Vt1okl2t6zKhP5Q8csl0met_403AsI0tHrahXVMHkiqNnt8FV-Bt4nPGWJOG92qpkRxmBpptFGcjOfXEHy86Fi3WCL94LLwVfBFgWY5VYGpx_WeBUev3LHesNvphdPsYVAupR3l2pGPOQCFbFZyjatbdWlUxAmkJCzOPvoqnSQRzfanKwBPKDfJXvFXC54hkr5zinvPUu90BhHMMZVf6-EWMFYj34RGM9WG1yO-ENed1HTDJ2aqtpP-ZH6_R88mKmgQAkSJualaluMHVg09TsxEyq0rXdk8EL1N5SRzZcFDswS0HeeICw
