POST http://localhost:8080/api/user-register
Content-Type: application/json

{ 
    "firstname": "Fabrizio",
    "lastname": "Mercurio" ,
    "password": "T4bUcchiolo!",
    "email": "mercurio.fabrizio@gmail.com",
    "city": null 
}

